name: fungus
channels:
  - menpo
  - defaults
dependencies:
  - blas
  - bokeh
  - ca-certificates
  - certifi
  - cffi
  - click
  - cloudpickle
  - cudatoolkit
  - cudnn
  - cycler
  - cytoolz
  - dask
  - dask-core
  - dbus
  - decorator
  - distributed
  - expat
  - fontconfig
  - freetype
  - glib
  - gst-plugins-base
  - gstreamer
  - heapdict
  - icu
  - imageio
  - intel-openmp
  - jinja2
  - jpeg
  - kiwisolver
  - libedit
  - libffi
  - libgfortran-ng
  - libpng
  - libtiff
  - libxml2
  - locket
  - markupsafe
  - matplotlib
  - mkl
  - mkl_fft
  - mkl_random
  - msgpack-python
  - ncurses
  - networkx
  - ninja
  - numpy
  - numpy-base
  - olefile
  - openssl
  - packaging
  - pandas
  - partd
  - pcre
  - pillow
  - pip
  - psutil
  - pycparser
  - pyparsing
  - pyqt
  - python
  - python-dateutil
  - pytz
  - pywavelets
  - pyyaml
  - qt
  - readline
  - scikit-image
  - scikit-learn
  - scipy
  - setuptools
  - sip
  - six
  - sortedcontainers
  - sqlite
  - tblib
  - tk
  - toolz
  - tornado
  - wheel
  - xz
  - yaml
  - zict
  - zlib
  - cyvlfeat
  - vlfeat
  - pip:
    - torch
    - torchvision
    - pytorch

